package com.example.commander.domain.message;

/**
 * Indicates how a report was triggered.
 *
 * <p>Distinguishes between reports generated by the scheduled batch process and
 * those requested on-demand by a user or external system.
 *
 * <p>Stored in {@code CAMT.ReportCommandAudit.trigger_type} for audit and
 * traceability purposes.
 */
public enum TriggerType {
    /** Report was triggered by the scheduled Quartz job. */
    SCHEDULED,

    /** Report was triggered by an on-demand request. */
    ON_DEMAND
}
